power = {'BUSES': {'Area': 3.73628,
           'Bus/Area': 3.73628,
           'Bus/Gate Leakage': 0.0100234,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.104523,
           'Bus/Subthreshold Leakage with power gating': 0.039196,
           'Gate Leakage': 0.0100234,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.104523,
           'Subthreshold Leakage with power gating': 0.039196},
 'Core': [{'Area': 329.51,
           'Execution Unit/Area': 290.915,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.202689,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.304033,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 1.67104,
           'Execution Unit/Instruction Scheduler/Area': 276.436,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.344008,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00133863,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 1.47529,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.411854,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0189035,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0104885,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 1.4358,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 16.6345,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.0861711,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 33.6528,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 2.43021,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 1.30614,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.744216,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 6307.35,
           'Execution Unit/Instruction Scheduler/ROB/Area': 259.458,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 1.34829,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 6272.22,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 380.305,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 14.1352,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 5.32408,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 383.147,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 15.4602,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 6.07878,
           'Execution Unit/Integer ALUs/Area': 1.88348,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.106116,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.335179,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.384742,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 1.60888,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.60333,
           'Execution Unit/Peak Dynamic': 6308.39,
           'Execution Unit/Register Files/Area': 7.29241,
           'Execution Unit/Register Files/Floating Point RF/Area': 2.50136,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.00224986,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0401938,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.0359316,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.0142611,
           'Execution Unit/Register Files/Gate Leakage': 0.00693828,
           'Execution Unit/Register Files/Integer RF/Area': 4.79105,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00468842,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.31994,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.327209,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.0719089,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.0275432,
           'Execution Unit/Register Files/Peak Dynamic': 0.31994,
           'Execution Unit/Register Files/Runtime Dynamic': 0.367402,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.10784,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.0418043,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.228414,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0300634,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.341705,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 3.50644,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.455805,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.170927,
           'Execution Unit/Runtime Dynamic': 387.913,
           'Execution Unit/Subthreshold Leakage': 18.9085,
           'Execution Unit/Subthreshold Leakage with power gating': 7.37324,
           'Gate Leakage': 2.04614,
           'Instruction Fetch Unit/Area': 11.7726,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.0039329,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.0039329,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00345415,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0013528,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00135,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.01267,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0366864,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.0694219,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.226166,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.000512573,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 28.57,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 1.06337,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00974314,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.00408438,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 5.74662,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.322633,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.367022,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.180386,
           'Instruction Fetch Unit/Instruction Decoder/Area': 7.43194,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 5.49615,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.306847,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 41.1821,
           'Instruction Fetch Unit/Runtime Dynamic': 1.7422,
           'Instruction Fetch Unit/Subthreshold Leakage': 1.00064,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.434359,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0880551,
           'L2/Runtime Dynamic': 0.0199468,
           'L2/Subthreshold Leakage': 0.834142,
           'L2/Subthreshold Leakage with power gating': 0.401066,
           'Load Store Unit/Area': 8.94469,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.01002,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.33557,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0450685,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0897099,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.08971,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 4.77826,
           'Load Store Unit/Runtime Dynamic': 1.8677,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.221209,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.442419,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.651446,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.30584,
           'Memory Management Unit/Area': 0.569577,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0785079,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0785896,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.0180657,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.357304,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0565673,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 1.29789,
           'Memory Management Unit/Runtime Dynamic': 0.135157,
           'Memory Management Unit/Subthreshold Leakage': 0.136735,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.06238,
           'Peak Dynamic': 7332.35,
           'Renaming Unit/Area': 8.37839,
           'Renaming Unit/FP Front End RAT/Area': 0.284555,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00465468,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 8.73591,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0482834,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.0275216,
           'Renaming Unit/Free List/Area': 2.1147,
           'Renaming Unit/Free List/Gate Leakage': 0.000500636,
           'Renaming Unit/Free List/Peak Dynamic': 1.88339,
           'Renaming Unit/Free List/Runtime Dynamic': 0.210297,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0134341,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00764574,
           'Renaming Unit/Gate Leakage': 0.10322,
           'Renaming Unit/Int Front End RAT/Area': 5.79908,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0848206,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 964.726,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 51.4201,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 1.02352,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.583404,
           'Renaming Unit/Peak Dynamic': 976.612,
           'Renaming Unit/Runtime Dynamic': 51.6304,
           'Renaming Unit/Subthreshold Leakage': 1.16502,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.648492,
           'Runtime Dynamic': 443.308,
           'Subthreshold Leakage': 24.5743,
           'Subthreshold Leakage with power gating': 9.92957}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.11798438438345697,
          'Runtime Dynamic': 0.11798438438345697,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.00849503,
         'Runtime Dynamic': 0.00599913,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 395.154,
               'Gate Leakage': 2.10458,
               'Peak Dynamic': 7332.36,
               'Peak Power': 7365.94,
               'Runtime Dynamic': 443.314,
               'Subthreshold Leakage': 31.4797,
               'Subthreshold Leakage with power gating': 13.6978,
               'Total Cores/Area': 329.51,
               'Total Cores/Gate Leakage': 2.04614,
               'Total Cores/Peak Dynamic': 7332.35,
               'Total Cores/Runtime Dynamic': 443.308,
               'Total Cores/Subthreshold Leakage': 24.5743,
               'Total Cores/Subthreshold Leakage with power gating': 9.92957,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.00849503,
               'Total L3s/Runtime Dynamic': 0.00599913,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 33.5843,
               'Total NoCs/Area': 3.73628,
               'Total NoCs/Gate Leakage': 0.0100234,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.104523,
               'Total NoCs/Subthreshold Leakage with power gating': 0.039196}}