power = {'BUSES': {'Area': 4.45794,
           'Bus/Area': 4.45794,
           'Bus/Gate Leakage': 0.0119594,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.124711,
           'Bus/Subthreshold Leakage with power gating': 0.0467668,
           'Gate Leakage': 0.0119594,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.124711,
           'Subthreshold Leakage with power gating': 0.0467668},
 'Core': [{'Area': 495.318,
           'Execution Unit/Area': 446.779,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.202689,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.304033,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 1.64169,
           'Execution Unit/Instruction Scheduler/Area': 409.13,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00146235,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 1.72302,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.593627,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0195747,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0105847,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 1.26296,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 60.828,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.31154,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 123.522,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 5.69214,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 4.72247,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 2.69123,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 25996.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 347.974,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 0.949955,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 25870.8,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 1008.9,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 11.4826,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 4.33162,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1015.19,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 16.2246,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 7.03344,
           'Execution Unit/Integer ALUs/Area': 3.76696,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.212233,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.425348,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.478605,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 3.21776,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 1.20666,
           'Execution Unit/Peak Dynamic': 25997.6,
           'Execution Unit/Register Files/Area': 28.3565,
           'Execution Unit/Register Files/Floating Point RF/Area': 9.63068,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.00825445,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0977772,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.128663,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.0497709,
           'Execution Unit/Register Files/Gate Leakage': 0.026159,
           'Execution Unit/Register Files/Integer RF/Area': 18.7258,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0179046,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.796009,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.81409,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.273097,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.103541,
           'Execution Unit/Register Files/Peak Dynamic': 0.796009,
           'Execution Unit/Register Files/Runtime Dynamic': 0.911868,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.40176,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.153311,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.273926,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0351536,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.282606,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 6.04999,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.53298,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.199868,
           'Execution Unit/Runtime Dynamic': 1023.13,
           'Execution Unit/Subthreshold Leakage': 21.7315,
           'Execution Unit/Subthreshold Leakage with power gating': 9.10119,
           'Gate Leakage': 2.02713,
           'Instruction Fetch Unit/Area': 21.801,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.0044456,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.0044456,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00391486,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00153889,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00172286,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0145289,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0410966,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.116615,
           'Instruction Fetch Unit/Instruction Buffer/Area': 2.64509,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.0346434,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 497.007,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 11.8038,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.290984,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.110014,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.43323,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.422052,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.367022,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.180386,
           'Instruction Fetch Unit/Instruction Decoder/Area': 14.8639,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 10.9923,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.391596,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 517.186,
           'Instruction Fetch Unit/Runtime Dynamic': 12.6731,
           'Instruction Fetch Unit/Subthreshold Leakage': 1.36057,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.569799,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0164588,
           'L2/Runtime Dynamic': 0.00455919,
           'L2/Subthreshold Leakage': 0.834142,
           'L2/Subthreshold Leakage with power gating': 0.401066,
           'Load Store Unit/Area': 9.12227,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.02316,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.34406,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0581307,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0901351,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0901351,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 5.24823,
           'Load Store Unit/Runtime Dynamic': 1.87871,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.222258,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.444516,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.73014,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.335351,
           'Memory Management Unit/Area': 0.747159,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.07888,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0789978,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.0311279,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.069572,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 2.19335,
           'Memory Management Unit/Runtime Dynamic': 0.14857,
           'Memory Management Unit/Subthreshold Leakage': 0.21543,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0918905,
           'Peak Dynamic': 26867.7,
           'Renaming Unit/Area': 7.93858,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 22.0682,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 2.42771,
           'Renaming Unit/Free List/Gate Leakage': 0.000363371,
           'Renaming Unit/Free List/Peak Dynamic': 2.30828,
           'Renaming Unit/Free List/Runtime Dynamic': 0.164463,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.00824939,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00437779,
           'Renaming Unit/Gate Leakage': 0.0402433,
           'Renaming Unit/Int Front End RAT/Area': 4.98475,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.00867665,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 318.553,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 11.2986,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.136044,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.0775451,
           'Renaming Unit/Peak Dynamic': 345.445,
           'Renaming Unit/Runtime Dynamic': 11.463,
           'Renaming Unit/Subthreshold Leakage': 0.346505,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.166279,
           'Runtime Dynamic': 1049.3,
           'Subthreshold Leakage': 27.0962,
           'Subthreshold Leakage with power gating': 11.3698}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.07339832340855919,
          'Runtime Dynamic': 0.07339832340855919,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.00765641,
         'Runtime Dynamic': 0.00425335,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 561.683,
               'Gate Leakage': 2.0875,
               'Peak Dynamic': 26867.7,
               'Peak Power': 26903.8,
               'Runtime Dynamic': 1049.31,
               'Subthreshold Leakage': 34.0217,
               'Subthreshold Leakage with power gating': 15.0822,
               'Total Cores/Area': 495.318,
               'Total Cores/Gate Leakage': 2.02713,
               'Total Cores/Peak Dynamic': 26867.7,
               'Total Cores/Runtime Dynamic': 1049.3,
               'Total Cores/Subthreshold Leakage': 27.0962,
               'Total Cores/Subthreshold Leakage with power gating': 11.3698,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.00765641,
               'Total L3s/Runtime Dynamic': 0.00425335,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 36.1092,
               'Total NoCs/Area': 4.45794,
               'Total NoCs/Gate Leakage': 0.0119594,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.124711,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0467668}}